### DISCUSSION TITLE
teleportToSpawnOnFirstJoin doesn't work

### DISCUSSION THREAD

**Discussion by HonzasikCZ** [EternalCodeTeam/EternalCore#769] [Support] [answered]
**Describe the bug**
The new player joins the server but it does not teleport him to the spawn

**To Reproduce**
Just join as new player

**Expected behavior**
If teleportToSpawnOnFirstJoin is set to true, it will teleport the new player to spawn

**Screenshots**
idk

**Platform (please complete the following information):**
 - Java Version: JDK 17
 - Server software: PurpurMC#2172 1.20.4

**Additional notes**
idk

**Comment by vLuckyyy** [comment]
I checked it, and... it works. I don't know what the problem might be that it doesn't work for you. Can you show yours `config.yml`?

**Comment by HonzasikCZ** [comment]
```
#
# This is the main configuration file for EternalCore.
#
# If you need help with the configuration or have any questions related to EternalCore, join us in our discord, or create an issue on our GitHub.
#
# Issues: https://github.com/EternalCodeTeam/EternalCore/issues
# Discord: https://discord.gg/FQ7jmGBd6c
# Website: https://eternalcode.pl/
# Source Code: https://github.com/EternalCodeTeam/EternalCore
#
# Whether the player should receive information about new plugin updates upon joining the server
shouldReceivePluginUpdates: true

# Database Section
database:
  # SQL Drivers and ports:
  # MySQL (3306), MariaDB (3306), PostgresQL (5432)
  # SQLite, H2
  databaseType: "SQLITE"
  hostname: "127.0.0.1"
  database: "database"
  username: "root"
  password: "U5eStr0ngP4ssw0rd"
  port: 3306

# Join settings
join:
  # Teleport to spawn on first join
  teleportToSpawnOnFirstJoin: true
  # Teleport to spawn on join
  teleportToSpawnOnJoin: false

# Teleport request section
teleportAsk:
  # Time of tpa requests expire
  
  # Time of tpa requests expire
  tpaRequestExpire: "1m20s"
  
  # Time of teleportation time in /tpa commands
  tpaTimer: "3s"

# Teleport section
teleport:
  # Teleports the player to spawn after death
  teleportToSpawnOnDeath: true
  # Teleports the player to respawn point after death
  teleportToRespawnPoint: true
  # Time of teleportation to spawn
  teleportTimeToSpawn: "5s"
  # Include players with op in teleport to random player
  includeOpPlayersInRandomTeleport: false

# Random Teleport Section
randomTeleport:
  # Type of random teleportation,
  # WORLD_BORDER_RADIUS - radius based on the world-border size.
  # STATIC_RADIUS - radius based on the manually value.
  randomTeleportType: "WORLD_BORDER_RADIUS"
  # Radius of random teleportation, this uses for starting point spawn via /setworldspawn.
  # If you want to use a static radius, set the type to STATIC_RADIUS and set the radius here.
  # If you using WORLD_BORDER_RADIUS, this value will be ignored.
  randomTeleportRadius: 1000
  # Teleport to a specific world, if left empty it will teleport to the player's current world
  randomTeleportWorld: "world"
  # Number of attempts to teleport to a random location
  randomTeleportAttempts: 10
  # Delay to request next random teleportation
  randomTeleportDelay: "1m"

# Homes Section
homes:
  # Default home name
  defaultHomeName: "domov"
  # Max homes per permission
  maxHomes:
    eternalcore.home.sponzor: 7
    eternalcore.home.media+: 6
    eternalcore.home.media: 5
    eternalcore.home.mvp: 5
    eternalcore.home.legend: 3
    eternalcore.home.vip: 2
    eternalcore.home.default: 1

# Awesome sounds
sound:
  # Do you want to enable sound after player join to server?
  enabledAfterJoin: true
  afterJoin: "BLOCK_NOTE_BLOCK_PLING"
  afterJoinVolume: 1.8
  afterJoinPitch: 1.0
  
  # Do you want to enable sound after player quit server?
  enableAfterQuit: true
  afterQuit: "BLOCK_NOTE_BLOCK_BASEDRUM"
  afterQuitVolume: 1.8
  afterQuitPitch: 1.0
  
  # Do you want to enable sound after player send message on chat server?
  enableAfterChatMessage: false
  afterChatMessage: "ENTITY_ITEM_PICKUP"
  afterChatMessageVolume: 1.8
  afterChatMessagePitch: 1.0

# Chat Section
chat:
  
  # Custom message for unknown command
  replaceStandardHelpMessage: false
  
  # Chat delay to send next message in chat
  chatDelay: "5s"
  
  # Number of lines that will be cleared when using the /chat clear command
  linesToClear: 160
  
  # Chat should be enabled?
  chatEnabled: true

# HelpOp Section
helpOp:
  # Delay to send the next message under /helpop
  helpOpDelay: "1m"

# Repair Section
repair:
  
  # Repair command cooldown
  repairDelay: "5s"

# Additional formatting options
format:
  separator: "&7, "

# AFK Section
afk:
  # Number of interactions a player must make to have AFK status removed
  # This is for so that stupid miss-click doesn't disable AFK status
  interactionsCountDisableAfk: 20
  
  # Time before using the /afk command again
  afkCommandDelay: "1m"
  # Should a player be marked as AFK automatically?
  # If set to true, the player will be marked as AFK after a certain amount of time of inactivity
  # If set to false, the player will have to use the /afk command to be marked as AFK
  autoAfk: true
  
  # The amount of time a player must be inactive to be marked as AFK
  afkInactivityTime: "10m"
  
  # Should a player be kicked from the game when marked as AFK?
  kickOnAfk: false

# Items
items:
  # Use unsafe enchantments? Allows you to apply custom enchants to various items
  unsafeEnchantments: true
  
  # The default item give amount, when no amount is specified in the command.
  defaultGiveAmount: 1

# Warp Section
warp:
  # Time of teleportation to warp's
  teleportTimeToWarp: "5s"
  # Warp inventory should be enabled?
  inventoryEnabled: true

# Butcher
butcher:
  # Safe number of chunks for command execution (above this number it will not be possible to execute the command)
  safeChunkNumber: 5

# AutoMessage Section
autoMessage:
  # AutoMessage should be enabled?
  enabled: false
  # Interval between messages
  interval: "5m"
  # Draw mode (RANDOM, SEQUENTIAL)
  drawMode: "RANDOM"
  # Minimum number of players on the server to send an auto message.
  minPlayers: 3

# Jail Section
jail:
  # Default jail duration, set if no duration is specified
  defaultJailDuration: "30m"
  # Allowed commands in jail
  allowedCommands:
    - "msg"
    - "help"
    - "r"
    - "tell"
    - "me"
```
