### ISSUE TITLE
Add custom command option.

### ISSUE THREAD

**Issue by vLuckyyy** [EternalCodeTeam/EternalCore#480]
I suggest adding the custom commands, which would allow users to create commands.

```yaml
vip: # /vip
  aliases:
    - vips
  notifications:
    chat:
      - "{prefix} <green><bold>Player <white>Notch <green>purchased <gold>VIP <green>for 7 days."
      - "{prefix} <aqua>Thank you for supporting our server <gold>VIP"
    actionbar: "<white><bold>New VIP status <gold>VIP"
    title: "<white><bold>New <gold>VIP"
    subtitle: "<aqua>Thank you for supporting our server"
    sound: "ENTITY_PLAYER_LEVELUP WEATHER 2.0 1.0"
  ```
