### ISSUE TITLE
Probably bug related to title & subtitle in configuration

### ISSUE THREAD

**Issue by Rollczi** [EternalCodeTeam/EternalCore#584]
e.g.
```yml
someMessage:
  title: siema
  subtitle: yo
```
set title to "siema"
set subtitle to "yo"
set title to ""
