### ISSUE TITLE
Add separated message to enable/disable.

### ISSUE THREAD

**Issue by vLuckyyy** [EternalCodeTeam/EternalCore#642]
```yaml
  # {STATE} - Status nieśmiertelności
  godMessage: "<green>► <white>Tryb nieśmiertelności został {STATE}"
  # {PLAYER} - Gracz któremu został ustawiony tryb nieśmiertelności, {STATE} - Status nieśmiertelności
  godSetMessage: "<green>► <white>Tryb nieśmiertelności dla gracza <green>{PLAYER} <white>został {STATE}"
  
  # {STATE} - Status latania
  flyMessage: "<green>► <white>Latanie zostało {STATE}"
  # {PLAYER} - Gracz któremu zostało ustawione latanie, {STATE} - Status latania
  flySetMessage: "<green>► <white>Latanie dla gracza <green>{PLAYER} <white>zostało {STATE}"
```

Like this:
```yaml
  socialSpyEnable: "<b><gradient:#00aeff:#00d9ff>SERWER</gradient></b> <dark_gray>➤</dark_gray> SocialSpy został <gradient:#00aeff:#00d9ff>włączone<white>!"
  socialSpyDisable: "<b><gradient:#00aeff:#00d9ff>SERWER</gradient></b> <dark_gray>➤</dark_gray> SocialSpy został <gradient:#00aeff:#00d9ff>wyłączone<white>!"
```
If someone don't want to use the {STATE} placeholder, you can configure separated messages.
