### ISSUE TITLE
[Addon] Display hologram above head when player is afk.

### ISSUE THREAD

**Issue by vLuckyyy** [EternalCodeTeam/EternalCore#680]
like this:

```yaml
format:
  - "item:BARRIER"
  - "This player is AFK!"
  - "Time: {TIME}"
```
