### ISSUE TITLE
AutoMessages console spam

### ISSUE THREAD

**Issue by HonzasikCZ** [EternalCodeTeam/EternalCore#692]
**Describe the bug**
It writes some warning to the console

**To Reproduce**
There are my automessages:
```
    1:
      chat:
        - ""
        - "                                   <b><color:#04a4fb>KLANY</color></b>"
        - "<center>Myslíš že jsi dobrý vůdce? Vytvoř si klan!"
        - "<center>Pozvi ostatní hráče a konkuruj celému serveru!"
        - "<#60fde9><center>/clans create <jméno klanu>"
        - ""
      sound: "BLOCK_ANVIL_BREAK 1.0 1.0"
    2:
      chat:
        - ""
        - "                               <b><color:#04a4fb>NAHLAŠOVÁNÍ</color></b>"
        - "<center>Myslíš že jsi našel chybu? nebo cheatera?"
        - "<center>Připoj se na náš discord server a vytvoř si ticket!"
        - "<click:open_url:'https://discord.gg/secretinvite'><#60fde9><center>https://discord.gg/secretinvite</click>"
        - ""
      sound: "BLOCK_ANVIL_BREAK 1.0 1.0"
```

**Expected behavior**
It should not write a warning to the console

**Screenshots**
![obrazek](https://github.com/EternalCodeTeam/EternalCore/assets/94143975/05d9ba0b-99ec-41fc-ba55-57fe78c9dcef)

**Platform (please complete the following information):**
 - Java Version: 17
 - Server software: Pufferfish-73 (MC: 1.19.4)

**Additional notes**
Nothing comes to my mind
