### ISSUE TITLE
Add a way to customize command usage

### ISSUE THREAD

**Issue by featxeven** [EternalCodeTeam/EternalCore#944]
![Image](https://github.com/user-attachments/assets/36be2c7c-5aa4-444c-8fe5-d53f8cf4bcef)

![Image](https://github.com/user-attachments/assets/6c4ad0b3-d05b-40fd-a1a6-caacf7fdffb0)

![Image](https://github.com/user-attachments/assets/2cd49837-2cd6-41f7-8b52-60b9625fcd33)

![Image](https://github.com/user-attachments/assets/a8ecfd5d-6517-48bb-9bb1-4fa8137b0f03)

Example of how it could look like on messages.yml:
```
privateChat:
  privateChatUsage: "<red>► <dark_red>Correct usage: /msg <player> <message>"

...

teleport:
  teleportUsage: "<red>► <dark_red>Correct usage: /tpa <player>"

...

chat:
  chatUsage:
    - "<red>► Correct usage:"
    - "<red>► /chat slowmode 0"
    - "<red>► /chat slowmode <duration>"
    - "<red>► /chat clear"

...
and so on!
```

This will allow even more customization on the messages section!
